[package]
name = "tsumego-solver"
version = "0.1.0"
authors = ["Cameron Martin <cameronmartin123@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
id_tree = "1.7.0"
im = "10.2.0"
sgf-parser = "2.4.0"

[dev-dependencies]
criterion = "0.3.1"

[[bench]]
name = "moves"
harness = false

[[bench]]
name = "unconditional_life"
harness = false
