[package]
name = "pn-search"
version = "0.1.0"
authors = ["Cameron Martin <cameronmartin123@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indextree = "4.0.0"
im = "10.2.0"

[dev-dependencies]
sgf-parser = "2.4.0"
